export const CREATE_PRESS_START = 500;
export const PROGRESS_START = CREATE_PRESS_START + 300;
const PROGRESS_DURATION = 4200 / 1.3 - 300;
export const PROGRESS_SPEED = 4200 / PROGRESS_DURATION;
export const PROGRESS_COMPLETE_START = PROGRESS_START + PROGRESS_DURATION;
