const CONTENT_DIR_PATH = 'content';
const DOCS_DIR_PATH = `${CONTENT_DIR_PATH}/docs`;
const FLOW_DIR_PATH = `${CONTENT_DIR_PATH}/flow`;
const USE_CASES_DIR_PATH = `${CONTENT_DIR_PATH}/use-cases`;
const CHANGELOG_DIR_PATH = `${CONTENT_DIR_PATH}/changelog`;

module.exports = { DOCS_DIR_PATH, FLOW_DIR_PATH, USE_CASES_DIR_PATH, CHANGELOG_DIR_PATH };
