const CONTENT_DIR_PATH = 'content';
const DOCS_DIR_PATH = `${CONTENT_DIR_PATH}/docs`;
const GUIDES_DIR_PATH = `${CONTENT_DIR_PATH}/guides`;
const FLOW_DIR_PATH = `${CONTENT_DIR_PATH}/flow`;
const FASTER_DIR_PATH = `${CONTENT_DIR_PATH}/faster`;
const CHANGELOG_DIR_PATH = `${CONTENT_DIR_PATH}/changelog`;
const POSTGRESQL_DIR_PATH = `${CONTENT_DIR_PATH}/postgresql`;
const TEMPLATE_PAGES_DIR_PATH = `${CONTENT_DIR_PATH}/pages`;
const USE_CASES_DIR_PATH = `${TEMPLATE_PAGES_DIR_PATH}/use-cases`;

module.exports = {
  DOCS_DIR_PATH,
  GUIDES_DIR_PATH,
  FLOW_DIR_PATH,
  FASTER_DIR_PATH,
  USE_CASES_DIR_PATH,
  CHANGELOG_DIR_PATH,
  POSTGRESQL_DIR_PATH,
  TEMPLATE_PAGES_DIR_PATH,
};
