export default {
  docs: '/docs/cloud/about/',
  team: '/team/',
  jobs: '/jobs/',
  community: '#',
  discord: 'https://discord.gg/YKY4CBXZT2',
  discussions: 'https://github.com/neondatabase/neon/discussions',
  github: 'https://github.com/neondatabase/neon',
  twitter: '/',
  postgresDocs: 'https://www.postgresql.org/docs/',
  postgresList: 'https://www.postgresql.org/list/',
  privacy: '/',
  terms: '/',
  dashboard: 'https://console.neon.tech/sign_in',
};
