export default {
  docs: '/docs/',
  team: '/team/',
  jobs: '/jobs/',
  community: '#',
  discord: 'https://discord.gg/YKY4CBXZT2',
  discussions: 'https://github.com/zenithdb/zenith/discussions',
  github: 'https://github.com/zenithdb/zenith',
  twitter: '/',
  postgresDocs: 'https://www.postgresql.org/docs/',
  postgresList: 'https://www.postgresql.org/list/',
  privacy: '/',
  terms: '/',
  dashboard: 'https://console.zenith.tech/sign_in',
};
