export default {
  docs: '/docs/cloud/about/',
  aboutUs: '/about-us/',
  careers: '/careers/',
  blog: '/blog/',
  earlyAccess: '/early-access/',
  security: '/docs/security/',
  releaseNotes: '/docs/release-notes/',
  discord: 'https://discord.gg/YKY4CBXZT2',
  discussions: 'https://github.com/neondatabase/neon/discussions',
  discourse: 'https://community.neon.tech',
  github: 'https://github.com/neondatabase/neon',
  twitter: 'https://twitter.com/neondatabase/',
  linkedin: 'https://www.linkedin.com/company/neon-inc/',
  postgresDocs: 'https://www.postgresql.org/docs/',
  postgresList: 'https://www.postgresql.org/list/',
  privacy: '/',
  terms: '/',
  dashboard: 'https://console.neon.tech/sign_in',
};
