text: ' We''re launching Compute, Object Storage, and AI Gateway to run alongside Database and Auth. Learn more and register for early access here.'
link:
  url: 'https://neon.com/blog/were-building-backends'
  target: '_blank'
