text: "Put an end to add-on fees. Neon includes SOC2, HIPAA, PrivateLink, Log Exports, PITR, SLAs on the Scale plan. 100% usage-based. No fixed fees."
link:
  url: 'https://neon.com/blog/why-we-no-longer-lock-premium-features'
  target: '_blank'
