text: 'Just shipped: Function Triggers - invoke a Neon Function when a file is uploaded to Object Storage'
link:
  url: 'https://neon.com/blog/when-a-file-is-uploaded-run-the-job-on-neon'
  target: '_blank'
