const AGENTS = {
  title: 'Apply for the Agent Plan',
  description: "Building an agent that needs databases? Let us know and we'll follow up promptly.",
  placeholder: 'URL for your Agent Platform',
  buttonText: 'Apply',
  eventName: 'Agent Plan Requested',
  eventProps: {
    name: 'region_name',
    id: 'region_id',
  },
};

const EXTENSIONS = {
  title: 'Request a new extension',
  description: 'Looking for a specific extension in Neon? Suggest one using this form.',
  placeholder: 'Select an extension',
  buttonText: 'Request',
  options: [
    { name: 'aiven_extras' },
    { name: 'adminpack' },
    { name: 'amcheck' },
    { name: 'auth_delay' },
    { name: 'auto_explain' },
    { name: 'aws_commons' },
    { name: 'aws_lambda' },
    { name: 'aws_s3' },
    { name: 'basebackup_to_shell' },
    { name: 'basic_archive' },
    { name: 'bool_plperl' },
    { name: 'bool_plperlu' },
    { name: 'cstore_fdw' },
    { name: 'Citus' },
    { name: 'dblink' },
    { name: 'dict_xsyn' },
    { name: 'file_fdw' },
    { name: 'flow_control' },
    { name: 'hstore_plperl' },
    { name: 'hstore_plperlu' },
    { name: 'http' },
    { name: 'jsonb_plperl' },
    { name: 'jsonb_plperlu' },
    { name: 'log_fdw' },
    { name: 'mongo_fdw' },
    { name: 'Multicorn' },
    { name: 'mysql_fdw' },
    { name: 'old_snapshot' },
    { name: 'oracle_fdw' },
    { name: 'orafce' },
    { name: 'pageinspect' },
    { name: 'passwordcheck' },
    { name: 'pg_anon' },
    { name: 'pg_bigm' },
    { name: 'pg_buffercache' },
    { name: 'pg_freespacemap' },
    { name: 'pg_parquet' },
    { name: 'pg_proctab' },
    { name: 'pg_similarity' },
    { name: 'pgSphere' },
    { name: 'pg_surgery' },
    { name: 'pg_transport' },
    { name: 'PGVectorStore' },
    { name: 'pg_visibility' },
    { name: 'pg_walinspect' },
    { name: 'pg_bulkload' },
    { name: 'pg_documentdb' },
    { name: 'pg_prometheus' },
    { name: 'pglogical' },
    { name: 'pldebugger' },
    { name: 'pljava' },
    { name: 'plperl' },
    { name: 'plperlu' },
    { name: 'plprofiler' },
    { name: 'pltcl' },
    { name: 'PL/Proxy' },
    { name: 'PostPic' },
    { name: 'Postgres_fdw' },
    { name: 'postgis_legacy' },
    { name: 'pgaudit' },
    { name: 'PgMemcache' },
    { name: 'rds_tools' },
    { name: 'sepgsql' },
    { name: 'sslinfo' },
    { name: 'tds_fdw' },
    { name: 'test_decoding' },
    { name: 'test_parser' },
    { name: 'Texcaller' },
    { name: 'timetravel' },
    { name: 'uuid' },
    { name: 'ZomboDB' },
  ],
  extendedOptions: true,
  eventName: 'Extension Requested',
  eventProps: {
    name: 'extension_name',
  },
};

const DATA = {
  agent: AGENTS,
  startup: EXTENSIONS,
  creator: AGENTS,
  openSource: AGENTS,
};

export default DATA;
