const BRANCH = process.env.BRANCH || 'dev';
const IS_PRODUCTION = BRANCH === 'main';
const GATSBY_ALGOLIA_INDEX_NAME = IS_PRODUCTION
  ? process.env.GATSBY_ALGOLIA_INDEX_NAME
  : process.env.GATSBY_ALGOLIA_INDEX_NAME_STAGING;

module.exports = {
  GATSBY_ALGOLIA_INDEX_NAME,
  IS_PRODUCTION,
};
