const REGIONS = {
  title: 'Request a new Provider / Region',
  description:
    "Looking for Neon in a different cloud provider or region? Select your preference below, and we'll notify you as soon as it's available.",
  placeholder: 'Select a region',
  buttonText: 'Request',
  options: [
    // AWS Regions
    { id: 'af-south-1', name: 'AWS - Africa (Cape Town)' },
    { id: 'ap-east-1', name: 'AWS - Asia Pacific (Hong Kong)' },
    { id: 'ap-northeast-1', name: 'AWS - Asia Pacific (Tokyo)' },
    { id: 'ap-northeast-2', name: 'AWS - Asia Pacific (Seoul)' },
    { id: 'ap-northeast-3', name: 'AWS - Asia Pacific (Osaka)' },
    { id: 'ap-south-1', name: 'AWS - Asia Pacific (Mumbai)' },
    { id: 'ap-south-2', name: 'AWS - Asia Pacific (Hyderabad)' },
    { id: 'ap-southeast-3', name: 'AWS - Asia Pacific (Jakarta)' },
    { id: 'ap-southeast-4', name: 'AWS - Asia Pacific (Melbourne)' },
    { id: 'ca-central-1', name: 'AWS - Canada (Central)' },
    { id: 'ca-west-1', name: 'AWS - Canada West (Calgary)' },
    { id: 'cn-north-1', name: 'AWS - China (Beijing)' },
    { id: 'cn-northwest-1', name: 'AWS - China (Ningxia)' },
    { id: 'eu-central-2', name: 'AWS - Europe (Zurich)' },
    { id: 'eu-north-1', name: 'AWS - Europe (Stockholm)' },
    { id: 'eu-south-1', name: 'AWS - Europe (Milan)' },
    { id: 'eu-south-2', name: 'AWS - Europe (Spain)' },
    { id: 'eu-west-1', name: 'AWS - Europe (Ireland)' },
    { id: 'eu-west-3', name: 'AWS - Europe (Paris)' },
    { id: 'il-central-1', name: 'AWS - Israel (Tel Aviv)' },
    { id: 'me-central-1', name: 'AWS - Middle East (UAE)' },
    { id: 'me-south-1', name: 'AWS - Middle East (Bahrain)' },
    { id: 'mx-central-1', name: 'AWS - North America (Mexico)' },
    { id: 'us-gov-east-1', name: 'AWS - AWS GovCloud (US-East)' },
    { id: 'us-gov-west-1', name: 'AWS - AWS GovCloud (US-West)' },
    { id: 'us-west-1', name: 'AWS - US West (N. California)' },

    // Azure Regions
    { id: 'australiaeast', name: 'Azure - (Asia Pacific) Australia East' },
    { id: 'australiacentral', name: 'Azure - (Asia Pacific) Australia Central' },
    { id: 'australiacentral2', name: 'Azure - (Asia Pacific) Australia Central 2' },
    { id: 'australiasoutheast', name: 'Azure - (Asia Pacific) Australia Southeast' },
    { id: 'centralindia', name: 'Azure - (Asia Pacific) Central India' },
    { id: 'eastasia', name: 'Azure - (Asia Pacific) East Asia' },
    { id: 'japaneast', name: 'Azure - (Asia Pacific) Japan East' },
    { id: 'japanwest', name: 'Azure - (Asia Pacific) Japan West' },
    { id: 'jioindiacentral', name: 'Azure - (Asia Pacific) Jio India Central' },
    { id: 'jioindiawest', name: 'Azure - (Asia Pacific) Jio India West' },
    { id: 'koreacentral', name: 'Azure - (Asia Pacific) Korea Central' },
    { id: 'koreasouth', name: 'Azure - (Asia Pacific) Korea South' },
    { id: 'southindia', name: 'Azure - (Asia Pacific) South India' },
    { id: 'westindia', name: 'Azure - (Asia Pacific) West India' },
    { id: 'centralus', name: 'Azure - (US) Central US' },
    { id: 'centraluseuap', name: 'Azure - (US) Central US EUAP' },
    { id: 'eastus', name: 'Azure - (US) East US' },
    { id: 'eastus2euap', name: 'Azure - (US) East US 2 EUAP' },
    { id: 'northcentralus', name: 'Azure - (US) North Central US' },
    { id: 'southcentralus', name: 'Azure - (US) South Central US' },
    { id: 'westcentralus', name: 'Azure - (US) West Central US' },
    { id: 'westus', name: 'Azure - (US) West US' },
    { id: 'westus2', name: 'Azure - (US) West US 2' },
    { id: 'brazilsouth', name: 'Azure - (South America) Brazil South' },
    { id: 'brazilus', name: 'Azure - (South America) Brazil US' },
    { id: 'brazilsoutheast', name: 'Azure - (South America) Brazil Southeast' },
    { id: 'canadacentral', name: 'Azure - (Canada) Canada Central' },
    { id: 'canadaeast', name: 'Azure - (Canada) Canada East' },
    { id: 'francecentral', name: 'Azure - (Europe) France Central' },
    { id: 'francesouth', name: 'Azure - (Europe) France South' },
    { id: 'germanynorth', name: 'Azure - (Europe) Germany North' },
    { id: 'italynorth', name: 'Azure - (Europe) Italy North' },
    { id: 'northeurope', name: 'Azure - (Europe) North Europe' },
    { id: 'norwayeast', name: 'Azure - (Europe) Norway East' },
    { id: 'norwaywest', name: 'Azure - (Europe) Norway West' },
    { id: 'polandcentral', name: 'Azure - (Europe) Poland Central' },
    { id: 'spaincentral', name: 'Azure - (Europe) Spain Central' },
    { id: 'swedencentral', name: 'Azure - (Europe) Sweden Central' },
    { id: 'switzerlandnorth', name: 'Azure - (Europe) Switzerland North' },
    { id: 'switzerlandwest', name: 'Azure - (Europe) Switzerland West' },
    { id: 'uksouth', name: 'Azure - (Europe) UK South' },
    { id: 'ukwest', name: 'Azure - (Europe) UK West' },
    { id: 'westeurope', name: 'Azure - (Europe) West Europe' },
    { id: 'israelcentral', name: 'Azure - (Middle East) Israel Central' },
    { id: 'qatarcentral', name: 'Azure - (Middle East) Qatar Central' },
    { id: 'uaecentral', name: 'Azure - (Middle East) UAE Central' },
    { id: 'uaenorth', name: 'Azure - (Middle East) UAE North' },
    { id: 'mexicocentral', name: 'Azure - (Mexico) Mexico Central' },
    { id: 'southafricanorth', name: 'Azure - (Africa) South Africa North' },
    { id: 'southafricawest', name: 'Azure - (Africa) South Africa West' },
    { id: 'asia-east1', name: 'GCP - Taiwan' },
    { id: 'asia-east2', name: 'GCP - Hong Kong' },
    { id: 'asia-northeast1', name: 'GCP - Tokyo' },
    { id: 'asia-northeast2', name: 'GCP - Osaka' },
    { id: 'asia-northeast3', name: 'GCP - Seoul' },
    { id: 'asia-south1', name: 'GCP - Mumbai' },
    { id: 'asia-south2', name: 'GCP - Delhi' },
    { id: 'asia-southeast1', name: 'GCP - Sydney' },
    { id: 'australia-southeast1', name: 'GCP - Sydney' },
    { id: 'australia-southeast2', name: 'GCP - Melbourne' },
    { id: 'europe-central2', name: 'GCP - Warsaw' },
    { id: 'europe-north1', name: 'GCP - Finland' },
    { id: 'europe-southwest1', name: 'GCP - Madrid' },
    { id: 'europe-west1', name: 'GCP - Belgium' },
    { id: 'europe-west2', name: 'GCP - London' },
    { id: 'europe-west3', name: 'GCP - Frankfurt' },
    { id: 'europe-west4', name: 'GCP - Netherlands' },
    { id: 'europe-west6', name: 'GCP - Zurich' },
    { id: 'europe-west8', name: 'GCP - Milan' },
    { id: 'europe-west9', name: 'GCP - Paris' },
    { id: 'northamerica-northeast1', name: 'GCP - Montréal' },
    { id: 'northamerica-northeast2', name: 'GCP - Toronto' },
    { id: 'southamerica-east1', name: 'GCP - Osasco' },
    { id: 'us-central1', name: 'GCP - Iowa' },
    { id: 'us-east1', name: 'GCP - South California' },
    { id: 'us-east4', name: 'GCP - Nothern Virginia' },
    { id: 'us-east5', name: 'GCP - Columbus' },
    { id: 'us-south1', name: 'GCP - Dallas' },
    { id: 'us-west1', name: 'GCP - Oregon' },
    { id: 'us-west2', name: 'GCP - Los Angeles' },
    { id: 'us-west3', name: 'GCP - Salt Lake City' },
  ],
  eventName: 'Region Requested',
  eventProps: {
    name: 'region_name',
    id: 'region_id',
  },
};

const EXTENSIONS = {
  title: 'Request a new extension',
  description: 'Looking for a specific extension in Neon? Suggest one using this form.',
  placeholder: 'Select an extension',
  buttonText: 'Request',
  options: [
    { name: 'aiven_extras' },
    { name: 'adminpack' },
    { name: 'amcheck' },
    { name: 'auth_delay' },
    { name: 'auto_explain' },
    { name: 'aws_commons' },
    { name: 'aws_lambda' },
    { name: 'aws_s3' },
    { name: 'basebackup_to_shell' },
    { name: 'basic_archive' },
    { name: 'bool_plperl' },
    { name: 'bool_plperlu' },
    { name: 'cstore_fdw' },
    { name: 'Citus' },
    { name: 'dblink' },
    { name: 'dict_xsyn' },
    { name: 'file_fdw' },
    { name: 'flow_control' },
    { name: 'hstore_plperl' },
    { name: 'hstore_plperlu' },
    { name: 'http' },
    { name: 'jsonb_plperl' },
    { name: 'jsonb_plperlu' },
    { name: 'log_fdw' },
    { name: 'mongo_fdw' },
    { name: 'Multicorn' },
    { name: 'mysql_fdw' },
    { name: 'old_snapshot' },
    { name: 'oracle_fdw' },
    { name: 'orafce' },
    { name: 'pageinspect' },
    { name: 'passwordcheck' },
    { name: 'pg_anon' },
    { name: 'pg_bigm' },
    { name: 'pg_buffercache' },
    { name: 'pg_freespacemap' },
    { name: 'pg_parquet' },
    { name: 'pg_proctab' },
    { name: 'pg_similarity' },
    { name: 'pgSphere' },
    { name: 'pg_surgery' },
    { name: 'pg_transport' },
    { name: 'PGVectorStore' },
    { name: 'pg_visibility' },
    { name: 'pg_walinspect' },
    { name: 'pg_bulkload' },
    { name: 'pg_documentdb' },
    { name: 'pg_prometheus' },
    { name: 'pglogical' },
    { name: 'pldebugger' },
    { name: 'pljava' },
    { name: 'plperl' },
    { name: 'plperlu' },
    { name: 'plprofiler' },
    { name: 'pltcl' },
    { name: 'PL/Proxy' },
    { name: 'PostPic' },
    { name: 'Postgres_fdw' },
    { name: 'postgis_legacy' },
    { name: 'pgaudit' },
    { name: 'PgMemcache' },
    { name: 'rds_tools' },
    { name: 'sepgsql' },
    { name: 'sslinfo' },
    { name: 'tds_fdw' },
    { name: 'test_decoding' },
    { name: 'test_parser' },
    { name: 'Texcaller' },
    { name: 'timetravel' },
    { name: 'uuid' },
    { name: 'ZomboDB' },
  ],
  extendedOptions: true,
  eventName: 'Extension Requested',
  eventProps: {
    name: 'extension_name',
  },
};

const DATA = {
  region: REGIONS,
  extension: EXTENSIONS,
};

export default DATA;
