#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Fallback paths for GUI git clients
export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin:$HOME/.npm-global/bin"

npx --no-install lint-staged --concurrent false