name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/cla.json'
          path-to-document: 'https://github.com/neondatabase/website/blob/main/CLA.md'
          allowlist: actions-user,dependabot[bot],devin-ai-integration[bot],danieltprice,bgrenon,rishi-raj-jain,carlotas19,saimonkat,americano98,yasell,vburlak,vannyle,andrewgolovanov,bobbyiliev,PaulieScanlon,andrelandgraf,dhanushreddy291,davidgomes,Boburmirzo
