name: E2E on Chrome

on:
  push:
    paths:
      - 'src/utils/forms.js'
      - 'src/constants/forms.js'
      - 'cypress/**'
      - 'src/components/shared/changelog-form/**'
      - 'src/components/pages/contact-sales/hero/contact-form/**'
      - 'src/components/pages/startups/hero/contact-form/**'
permissions:
  contents: read

jobs:
  install:
    runs-on:
      group: neondatabase-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@108b8684ae52e735ff7891524cbffbcd4be5b19f # v6.7.16
        with:
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
        env:
          NEXT_PUBLIC_DEFAULT_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_GITHUB_PATH: ${{ secrets.NEXT_PUBLIC_GITHUB_PATH }}
