name: Linkinator

on:
  schedule:
    - cron: '0 0 * * 1'

env:
  GATSBY_DEFAULT_SITE_URL: https://neon.com
permissions:
  contents: read

jobs:
  linkinator:
    name: 'Checks broken links'
    runs-on:
      group: neondatabase-protected-runner-group
      labels: linux-ubuntu-latest
    continue-on-error: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: JustinBeckwith/linkinator-action@3d5ba091319fa7b0ac14703761eebb7d100e6f6d # v1.11.0
        with:
          paths: ${{ env.GATSBY_DEFAULT_SITE_URL }}
          concurrency: 100
          recurse: true
          retry: true
          skip: ".*(\\.js|\\.css|\\.woff2)$"
          linksToSkip: >-
            linkedin.com,
            googleapis.com
          verbosity: 'ERROR'
          markdown: false
