name: Linkinator

on:
  schedule:
    - cron: '0 0 * * 1'

env:
  GATSBY_DEFAULT_SITE_URL: https://neon.com
permissions:
  contents: read

jobs:
  linkinator:
    name: 'Checks broken links'
    runs-on:
      group: neondatabase-protected-runner-group
      labels: linux-ubuntu-latest
    continue-on-error: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: JustinBeckwith/linkinator-action@3d5ba091319fa7b0ac14703761eebb7d100e6f6d # v1.11.0
        with:
          paths: ${{ env.GATSBY_DEFAULT_SITE_URL }}
          concurrency: 100
          recurse: true
          retry: true
          skip: ".*(\\.js|\\.css|\\.woff2)$"
          linksToSkip: >-
            linkedin.com,
            googleapis.com
          verbosity: 'ERROR'
          markdown: false
