name: Linkinator

on:
  schedule:
    - cron: '0 0 * * 1'

env:
  GATSBY_DEFAULT_SITE_URL: https://neon.com
permissions:
  contents: read

jobs:
  linkinator:
    name: 'Checks broken links'
    runs-on:
      group: neondatabase-protected-runner-group
      labels: linux-ubuntu-latest
    continue-on-error: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: JustinBeckwith/linkinator-action@7b6b0bc671f6264e1a8daa4488a5bd91ce61dcd4 # v2.4.2
        with:
          paths: ${{ env.GATSBY_DEFAULT_SITE_URL }}
          concurrency: 100
          recurse: true
          retry: true
          skip: ".*(\\.js|\\.css|\\.woff2)$"
          linksToSkip: >-
            linkedin.com,
            googleapis.com
          verbosity: 'ERROR'
          markdown: false
